from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
profile = webdriver.FirefoxProfile()
capabilities = webdriver.DesiredCapabilities().FIREFOX
capabilities['acceptSslCerts'] = True
profile.set_preference("security.ssl3.dhe_rsa_aes_128_sha", True)
profile.set_preference("security.ssl3.dhe_rsa_aes_256_sha", True)
profile.set_preference("app.normandy.startupRolloutPrefs.security.tls.version.min", 1)
profile.set_preference("security.tls.insecure_fallback_hosts", 'http://192.168.2.52')
profile.set_preference("security.tls.version.enable-deprecated", True)
#profile.set_preference("security.warn_leaving_secure", False)
#profile.set_preference("security.warn_leaving_insecure", False)
#profile.set_preference("browser.aboutConfig.showWarning", False)
browser = webdriver.Firefox(executable_path="./drivers/geckodriver", firefox_profile=profile)
browser.get('http://192.168.2.52')
sleep(20)
browser.switch_to_frame("modalFrame")
searchInput = browser.find_element_by_name('usernameInput')
searchInput.click()
searchInput.send_keys('admin')
searchInput = browser.find_element_by_name('passwordInput')
searchInput.send_keys('35126249' + Keys.ENTER)
sleep(10)
browser.switch_to_default_content()
browser.switch_to_frame("appFrame")
browser.switch_to_frame("frameDirectory")
button = browser.find_element_by_id('tree_pwrMgmt')
button.click()
button = browser.find_element_by_id('nav_pwrServer')
button.click()
browser.switch_to_default_content()
browser.switch_to_frame("appFrame")
browser.switch_to_frame("frameContent")
browser.switch_to_frame("iframeContent")
sleep(5)
try :
    button = browser.find_element_by_id('HoldButton')
    button.click()
    print("hold button found")
except:
    print("no hold button")
    button = browser.find_element_by_id('PressButton')
    button.click()
sleep(1)
popup = browser.switch_to.alert
sleep(1)
popup.accept()
sleep(10)
browser.quit()
