#!/bin/bash
sleep 30
rm main1_log
cd /home/gui-bot/Desktop/Scripts/GUI/
echo "started ILO script"
echo "started ILO script" >> main1_log
i=0
o=0

while :
do
sleep 1
xdotool click 1
i=$(( $i + 1))
if [ $i == 100 ]
then
i=0
o=$(( $o + 1 ))
echo "check loop done $o hundred"
echo "check loop done $o hundred" >> main1_log
fi
xdotool mousemove 1152 4

cd /home/homeassistant/.homeassistant/Scripts/GUI/
flag1=$(cat flag1)
if [ $flag1 == "1" ]
then
messege=$(cat flag2)
echo 0 > flag1
else
messege=""
fi
cd /home/gui-bot/Desktop/Scripts/GUI/

if [ "$messege" == "Wake up vault" ]
then
  echo "waking up the vault"
  date
  echo "waking up the vault" >> main1_log
  date >> main1_log
  python3 vault.py
fi

if [ "$messege" == "Wake up g585" ]
then
  echo "waking up g585"
  date
  echo "waking up g585" >> main1_log
  date >> main1_log
  python3 g585.py
fi

if [ "$messege" == "Wake up gser" ]
then
  echo "waking up gser"
  date
  echo "waking up gser" >> main1_log
  date >> main1_log
  python3 gser.py
fi

if [ "$messege" == "Shutdown vault" ]
then
  echo "shuting down vault"
  date
  echo "shuting down vault" >> main1_log
  date >> main1_log
  python3 vault.py
fi

if [ "$messege" == "Shutdown g585" ]
then
  echo "shuting down g585"
  date
  echo "shuting down g585" >> main1_log
  date >> main1_log
  python3 g585.py
fi

if [ "$messege" == "Shutdown gser" ]
then
  echo "shuting down gser"
  date
  echo "shuting gown gser" >> main1_log
  date >> main1_log
  python3 gser.py
fi

done
